pipeline {
    agent { label 'Jenkins_Agent' }

    tools {
        jdk 'Java17'
        maven 'Maven3'
    }

    stages {
        stage("Cleanup Workspace") {
            steps {
                echo "Cleaning up workspace..."
                cleanWs()
            }
        }

        stage("Checkout from SCM") {
            steps {
                echo "Checking out code from SCM..."
                git branch: 'ramesh', credentialsId: 'github', url: 'https://github.com/ramesh1918s/My_Projects.git'
            }
        }

        stage("Build Application") {
            steps {
                echo "Building the application..."
                dir('register-app') { // Navigate to the correct directory
                    sh "mvn clean package"
                }
            }
        }

        stage("Test Application") {
            steps {
                echo "Running tests on the application..."
                dir('register-app') { // Navigate to the correct directory
                    sh "mvn test"
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully."
        }
        failure {
            echo "Pipeline failed. Check the logs for more details."
        }
        always {
            echo "Cleaning up workspace after build..."
            cleanWs()
        }
    }
}
