pipeline {
    agent { label 'Jenkins_Agent' }
    tools {
        jdk 'Java17'
        maven 'Maven3'
    }

stages{
        stage("Cleanup Workspace"){
                steps {
                cleanWs()
                }
        }

        stage("Checkout from SCM"){
                steps {
                    git branch: 'ramesh', credentialsId: 'github', url: 'https://github.com/ramesh1918s/My_Projects.git'
                }
        }

        stage("Build Application"){
            steps {
                sh "mvn clean package"
            }

       }

       stage("Test Application"){
           steps {
                 sh "mvn test"
           }
      
         }
     }
 }